# Numpy
Numerical computing package in python! It's core type is ndarray(numpy array)! Supports high vector matrix and high dimensional data structures for python!

In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3,4]) #1D array - it stores elements of same type

In [3]:
np1

array([1, 2, 3, 4])

In [4]:
type(np1)

numpy.ndarray

In [5]:
np1[0] = 5 #manipulation

In [12]:
np1

array([5, 2, 3, 4])

In [13]:
np1.shape

(4,)

In [19]:
mat1 = np.array([[1,2],[3,4]])

In [20]:
mat1

array([[1, 2],
       [3, 4]])

In [21]:
type(mat1)

numpy.ndarray

In [22]:
mat1.shape

(2, 2)

In [23]:
mat1[0]=5

In [24]:
mat1

array([[5, 5],
       [3, 4]])

In [25]:
mat1[0][1]=6

In [26]:
mat1

array([[5, 6],
       [3, 4]])

In [27]:
mat1[0][1] = "str" #gives an error because all other elements in the array are of type!

ValueError: invalid literal for int() with base 10: 'str'

In [29]:
mat2 = np.arange(0,10,1) #here the last element is not included which is 10!!

In [48]:
mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
type(mat2)

numpy.ndarray

In [31]:
mat3 = np.linspace(0,10,20) #the last element is also included. It gives us a 1D array with 20 randomam values in the range of 1-10 

In [46]:
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [47]:
type(mat3)

numpy.ndarray

In [33]:
mat3.shape

(20,)

In [34]:
mat4 = np.random.rand(5,5) #generating a 5*5 random matrix

In [35]:
mat4

array([[0.71328548, 0.14031008, 0.64989282, 0.81791778, 0.14251425],
       [0.96365666, 0.66534631, 0.43806429, 0.68992963, 0.95495149],
       [0.23143722, 0.25466692, 0.11045787, 0.49255494, 0.97785138],
       [0.08099181, 0.47296693, 0.63247922, 0.49020482, 0.1589271 ],
       [0.43612565, 0.72239442, 0.47863309, 0.01063296, 0.38686699]])

In [36]:
mat4.shape

(5, 5)

In [39]:
mat5 = np.random.randn(5,5) #normally distributed random matrix

In [51]:
mat5

array([[ 1.16318785,  0.61818048, -1.47290887, -0.89828804,  1.63304743],
       [ 0.22534661, -1.3469793 , -0.46562382,  0.26290886, -0.60642733],
       [ 0.70453647,  1.10117695, -0.67374626, -1.62554685,  0.78655582],
       [ 0.62526003,  0.53024236, -0.78734138,  0.06806634, -0.37161511],
       [-0.55259658,  0.10582643, -1.36828911, -0.39086949, -0.49112682]])

In [52]:
type(mat5)

numpy.ndarray

* np.diag
* np.zeros
+ np.ones

In [41]:
mat5[0]

array([ 1.16318785,  0.61818048, -1.47290887, -0.89828804,  1.63304743])

In [42]:
mat5[0,0] #0th row, 0th element

1.1631878536829077

In [43]:
mat5[0,1] #0th row, 1st element

0.6181804789707791

In [44]:
mat5[0:1] #first row

array([[ 1.16318785,  0.61818048, -1.47290887, -0.89828804,  1.63304743]])

In [45]:
mat5[0:3,:] #first three rows and all columns

array([[ 1.16318785,  0.61818048, -1.47290887, -0.89828804,  1.63304743],
       [ 0.22534661, -1.3469793 , -0.46562382,  0.26290886, -0.60642733],
       [ 0.70453647,  1.10117695, -0.67374626, -1.62554685,  0.78655582]])

# pandas
pandas is used for manipulation and analysis!